traffic/urls.py
from django.contrib import admin
from django.urls import path, include
from trafficapp import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('trafficapp/', include('trafficapp.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special')
]

trafficapp/urls.py
from django.urls import path
from trafficapp import views

app_name = 'trafficapp'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('admin/dashboard/', views.admindashboard, name='admindashboard'),
    path('admin/packages/', views.adminpackages, name='adminpackages'),
    path('admin/orders/', views.ordersplaced, name='ordersplaced'),
    path('admin/users/', views.userlist, name='userlist'),
    path('user/dashboard/', views.userdashboard, name='userdashboard'),
    path('user/packages/', views.userpackages, name='userpackages'),
    path('user/placeorder/', views.placeorder, name='placeorder'),
    path('user/history/', views.history, name='history'),
    path('traffic_request/', views.traffic_request, name='traffic_request'),
    path('generate_traffic/', views.generate_traffic, name='generate_traffic'),
]

trafficapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class TrafficGenerateRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=None)

    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    company = models.CharField(max_length=255)
    url = models.CharField(max_length=255)
    minimum = models.IntegerField()
    maximum = models.IntegerField()
    requests = models.IntegerField()
    stay = models.IntegerField()

    def __str__(self):
        return self.user.username

trafficapp/forms.py
from django import forms
from django.contrib.auth.models import User
from trafficapp.models import TrafficGenerateRequest

class UserForm(forms.ModelForm):
    password = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')

class TrafficRequestForm(forms.ModelForm):
    class Meta:
        model = TrafficGenerateRequest
        fields = ('name', 'email', 'company', 'url', 'minimum', 'maximum', 'requests', 'stay')

trafficapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from trafficapp.forms import UserForm, TrafficRequestForm
from .models import TrafficGenerateRequest

from subprocess import check_output, run, PIPE
import sys 
import os

# Create your views here.
def index(request):
    return render(request, 'trafficapp/index.html')

# Register & Log In Views

@login_required
def special(request):
    return HttpResponse("You did it")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            registered = True
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()
    
    return render(request, 'trafficapp/registration.html', {'user_form': user_form, 'registered':registered})

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        
        if user:
            if user.is_active and user.is_superuser:
                login(request,user)
                return redirect('/trafficapp/admin/dashboard/', pk=user.username)
            else:
                login(request,user)
                return redirect('/trafficapp/user/dashboard/', pk=user.username) 
        else:
            print("Login Failed")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Invalid Details")
    else:
        return render(request, 'trafficapp/login.html',{})

# Admin Views

@login_required
def admindashboard(request):
    return render(request, 'trafficapp/admin/dashboard.html')

@login_required
def ordersplaced(request):
    obj = TrafficGenerateRequest.objects.all()
    context = {
        'objects': obj
    }
    return render(request, 'trafficapp/admin/orders.html', context)
    #return render(request, 'trafficapp/admin/orders.html')

@login_required
def adminpackages(request):
    return render(request, 'trafficapp/admin/packages.html')

@login_required
def userlist(request):
    return render(request, 'trafficapp/admin/users.html')

# User Views

@login_required
def userdashboard(request):
    return render(request, 'trafficapp/user/dashboard.html')

@login_required
def placeorder(request):
    return render(request, 'trafficapp/user/placeorder.html')

@login_required
def userpackages(request):
    return render(request, 'trafficapp/user/packages.html')

@login_required
def history(request):
    return render(request, 'trafficapp/user/history.html')

# Traffic Process URLs

@login_required
def traffic_request(request):
    if request.method == "POST":
        traffic_request_form = TrafficRequestForm(data=request.POST)

        if traffic_request_form.is_valid():
            traffic_request = traffic_request_form.save(commit=False)
            traffic_request.user = request.user
            traffic_request.save()
        else:
            print(traffic_request_form.errors)
    else:
        traffic_request_form = TrafficRequestForm()
    
    return redirect('/trafficapp/user/dashboard/')

@login_required
def generate_traffic(request):
    pk_id = request.GET['id']
    user = request.GET['user']
    url = request.GET['url']
    minimum = request.GET['minimum']
    maximum = request.GET['maximum']
    requests = request.GET['requests']
    stay = request.GET['stay']

    #output = check_output([python traffic.py, "--domain" , url])
    #print(sys.argv)
    out = run([sys.executable, 'C://Users//Maisum Abbas//learning_users//trafficapp//traffic.py', "--domain", url, "--threads", '5', "--max-clicks", maximum, "--min-clicks", minimum, "--stay", stay, "--requests", requests])
    #os.system(out)
    return redirect('/trafficapp/admin/dashboard/')

templates/trafficapp/admin/footer.html
<footer class="footer">
    <div class="container-fluid">
        <nav class="float-left">
        <ul>
            <li>
            <a href="#">
                Traffic Generator
            </a>
            </li>
            <li>
            <a href="">
                About Us
            </a>
            </li>
            <li>
            <a href="">
                Licenses
            </a>
            </li>
        </ul>
        </nav>
        <div class="copyright float-right">
        &copy;
        <script>
            document.write(new Date().getFullYear())
        </script> Powered By
        <a href="https://www.esquall.com/" target="_blank"><b>eSquall Inc.</b></a>
        </div>
    </div>
</footer>

templates/trafficapp/admin/head.html
{% load static %}

<meta charset="utf-8" />
<link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
<link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
<!--     Fonts and icons     -->
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
<!-- CSS Files -->
<link href="{% static 'assets/css/material-dashboard.css' %}" rel="stylesheet" />
<!-- CSS Just for demo purpose, don't include it in your project -->
<link href="{% static 'assets/demo/demo.css' %}" rel="stylesheet" />
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

templates/trafficapp/admin/orders.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    {% include "trafficapp/admin/head.html" %}
    <title>
      Orders Placed | Traffic Generator
    </title>
  </head>

  <body class="">
    <div class="wrapper ">
      {% include "trafficapp/admin/sidebar.html" %}
      <div class="main-panel">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
          <div class="container-fluid">
            <div class="navbar-wrapper">
              <div class="navbar-minimize">
                <!--<button id="minimizeSidebar" class="btn btn-just-icon btn-white btn-fab btn-round">
                  <i class="material-icons text_align-center visible-on-sidebar-regular">more_vert</i>
                  <i class="material-icons design_bullet-list-67 visible-on-sidebar-mini">view_list</i>
                </button>-->
              </div>
              <a class="navbar-brand" href="javascript:;">Orders Placed</a>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
              <span class="sr-only">Toggle navigation</span>
              <span class="navbar-toggler-icon icon-bar"></span>
              <span class="navbar-toggler-icon icon-bar"></span>
              <span class="navbar-toggler-icon icon-bar"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="/trafficapp/admin/dashboard">
                    <i class="material-icons">dashboard</i>
                    <p class="d-lg-none d-md-block">
                      Stats
                    </p>
                  </a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="material-icons">person</i>
                    <p class="d-lg-none d-md-block">
                      Account
                    </p>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                    <a class="dropdown-item" href="#">Profile</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
        <div class="content">
          <div class="content">
            <div class="container-fluid">
              <div class="row">
              <div class="col-md-12">
                <div class="card">
                  <div class="card-header card-header-success card-header-icon">
                    <div class="card-icon">
                      <i class="material-icons">supervisor_account</i>
                    </div>
                    <h4 class="card-title">Orders Placed</h4>
                  </div>
                  <div class="card-body">
                    <div class="toolbar">
                      <!--        Here you can write extra buttons/actions for the toolbar              -->
                    </div>
                    <div class="material-datatables">
                      <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0">
                        <thead>
                          <tr>
                            <th>Id</th>
                            <th>Username</th>
                            <th>Url</th>
                            <th>Minimum</th>
                            <th>Maximum</th>
                            <th>Requests</th>
                            <th>Stay</th>
                            <th class="disabled-sorting text-Centre">Generate</th>
                          </tr>
                        </thead>
                        <tfoot>
                          <tr>
                            <th>Id</th>
                            <th>Username</th>
                            <th>Url</th>
                            <th>Minimum</th>
                            <th>Maximum</th>
                            <th>Requests</th>
                            <th>Stay</th>
                            <th class="disabled-sorting text-Centre">Generate</th>
                          </tr>
                        </tfoot>
                        <tbody>
                          {% for object in objects %}
                          <tr>
                            <td>{{ object.id }}</td>
                            <td>{{ object.user }}</td>
                            <td>{{ object.url }}</td>
                            <td>{{ object.minimum }}</td>
                            <td>{{ object.maximum }}</td>
                            <td>{{ object.requests }}</td>
                            <td>{{ object.stay }}</td>
                            <td class="text-centre">
                              <a href="{% url 'trafficapp:generate_traffic' %}?id={{object.id}}&user={{object.user}}&url={{object.url}}&minimum={{object.minimum}}&maximum={{object.maximum}}&requests={{object.requests}}&stay={{object.stay}}" class="btn btn-danger btn-round remove">Run<!--<i class="material-icons">close</i>--></a>
                            </td>
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
                  <!-- end content-->
                </div>
                <!--  end card  -->
              </div>
              </div>
            </div>
          </div>
        </div>
        {% include "trafficapp/admin/footer.html" %}
      </div>
    </div>
    {% include "trafficapp/admin/foot.html" %}
  </body>
</html>

templates/trafficapp/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Base</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navabr-nav">
                    <li><a class="navabr-brand" href="{% url 'index' %}">DJANGO</a></li>
                    <li><a class="navabr-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class="navabr-link" href="{% url 'trafficapp:register' %}">Register</a></li>
                    {% if user.is_authenticated %}
                        <li><a class="navabr-link" href="{% url 'logout' %}">Log Out</a></li>
                    {% else %}
                        <li><a class="navabr-link" href="{% url 'trafficapp:user_login' %}">Log In</a></li>
                    {% endif %}
                    
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>
    </body>
</html>

templates/trafficapp/header.html
{% load static %}
<header id="header" class="header-transparent header-effect-shrink" data-plugin-options="{'stickyEnabled': true, 'stickyEffect': 'shrink', 'stickyEnableOnBoxed': true, 'stickyEnableOnMobile': true, 'stickyChangeLogo': true, 'stickyStartAt': 30, 'stickyHeaderContainerHeight': 70}">
    <div class="header-body border-top-0 bg-dark box-shadow-none">
        <div class="header-container container">
            <div class="header-row">
                <div class="header-column">
                    <div class="header-row">
                        <div class="header-logo">
                            <a href="#">
                                <img alt="Analytics" width="82" height="40" src="{% static 'img/logo-default-slim-dark.png' %}">
                            </a>
                        </div>
                    </div>
                </div>
                <div class="header-column justify-content-end">
                    <div class="header-row">
                        <div class="header-nav header-nav-links header-nav-dropdowns-dark header-nav-light-text order-2 order-lg-1">
                            <div class="header-nav-main header-nav-main-mobile-dark header-nav-main-square header-nav-main-dropdown-no-borders header-nav-main-effect-2 header-nav-main-sub-effect-1">
                                <nav class="collapse">
                                    <ul class="nav nav-pills" id="mainNav">
                                        <li class="dropdown">
                                            <a data-hash class="dropdown-item active" href="#home">
                                                Home
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" data-hash data-hash-offset="68" href="#services">Services</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" data-hash data-hash-offset="68" href="#packages">Packages</a>
                                        </li>
                                        <!--<li>
                                            <a class="dropdown-item" data-hash data-hash-offset="68" href="#sign">Sign In/Up</a>
                                        </li>-->
                                        <li>
                                            <a class="dropdown-item" data-hash data-hash-offset="68" href="#contact">Contact Us</a>
                                        </li>
                                        {% if user.is_authenticated %}
                                        <li>
                                            <a class="dropdown-item" data-hash data-hash-offset="68" href="{% url 'logout' %}">Log Out</a>
                                        </li>
                                        {% else %}
                                        <li>
                                            <a class="dropdown-item" data-hash data-hash-offset="68" href="{% url 'trafficapp:user_login' %}">Log In</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" data-hash data-hash-offset="68" href="{% url 'trafficapp:register' %}">Sign Up</a>
                                        </li>
                                        {% endif %}
                                    </ul>
                                </nav>
                            </div>
                            <button class="btn header-btn-collapse-nav" data-toggle="collapse" data-target=".header-nav-main nav">
                                <i class="fas fa-bars"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

templates/trafficapp/login.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
        <title>Traffic Generator</title>	
        {% include "trafficapp/head.html" %}
    </head>
    <body class="one-page" data-target="#header" data-spy="scroll" data-offset="100">
        <div class="body">
            {% include "trafficapp/header.html" %}
            
            <div role="main" class="main">
                <section class="page-header page-header-classic">
                    <br><br>
                    <div class="container">
                        <div class="row">
                            <div class="col">
                                <ul class="breadcrumb">
                                    <li><a href="{% url 'index' %}">Home</a></li>
                                    <li class="active">Pages</li>
                                </ul>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col p-static">
                                <h1 data-title-border>Login</h1>
                            </div>
                        </div>
                    </div>
                </section>

                <div class="container">

                    <div class="row">
                        <div class="col">

                            <div class="featured-boxes">
                                <div class="row">
                                    <div class="col-md-3"></div>
                                    <div class="col-md-6">
                                        <div class="featured-box featured-box-primary text-left mt-5">
                                            <div class="box-content">
                                                <h4 class="color-primary font-weight-semibold text-4 text-uppercase mb-3">I'm a Returning Client</h4>
                                                <form action="{% url 'trafficapp:user_login' %}" id="frmSignIn" method="post" class="needs-validation">
                                                    {% csrf_token %}
                                                    <div class="form-row">
                                                        <div class="form-group col">
                                                            <label class="font-weight-bold text-dark text-2">Username</label>
                                                            <input type="text" class="form-control fomr-control-lg" name="username" required autocomplete="username" autofocus>
                                                        </div>
                                                    </div>
                                                    <div class="form-row">
                                                        <div class="form-group col">
                                                                <a href="#" class="float-right">(Lost Password?)</a>
                                                            <label class="font-weight-bold text-dark text-2">Password</label>
                                                            <input type="password" class="form-control form-control-lg" name="password" required autocomplete="current-password">
                                                        </div>
                                                    </div>
                                                    <div class="form-row">
                                                        <div class="form-group col-lg-6">
                                                            <div class="custom-control custom-checkbox">
                                                                <input type="checkbox" class="custom-control-input" id="rememberme">
                                                                <label class="custom-control-label text-2" for="rememberme">Remember Me</label>
                                                            </div>
                                                        </div>
                                                        <div class="form-group col-lg-6">
                                                            <input type="submit" value="Login" class="btn btn-primary btn-modern float-right" data-loading-text="Loading...">
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3"></div>
                                </div>

                            </div>
                        </div>
                    </div>

                </div>

            </div>
        
			{% include "trafficapp/footer.html" %}
		</div>
		{% include "trafficapp/foot.html" %}
    </body>
</html>

templates/trafficapp/registration.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
        <title>Traffic Generator</title>	
        {% include "trafficapp/head.html" %}
    </head>
    <body class="one-page" data-target="#header" data-spy="scroll" data-offset="100">
        <div class="body">
            {% include "trafficapp/header.html" %}
            
            <div role="main" class="main">
                <section class="page-header page-header-classic">
                    <br><br>
                    <div class="container">
                        <div class="row">
                            <div class="col">
                                <ul class="breadcrumb">
                                    <li><a href="{% url 'index' %}">Home</a></li>
                                    <li class="active">Pages</li>
                                </ul>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col p-static">
                                <h1 data-title-border>Register</h1>
                            </div>
                        </div>
                    </div>
                </section>

                <div class="container">

					<div class="row">
						<div class="col">

							<div class="featured-boxes">
								<div class="row">
                                    <div class="col-md-3"></div>
									<div class="col-md-6">
										<div class="featured-box featured-box-primary text-left mt-5">
											<div class="box-content">
												<h4 class="color-primary font-weight-semibold text-4 text-uppercase mb-3">Sign Me Up</h4>
												<form action="{% url 'trafficapp:register' %}" id="frmSignIn" method="post" class="needs-validation">
                                                    {% csrf_token %}
                                                    <div class="form-row">
														<div class="form-group col">
															<label class="font-weight-bold text-dark text-2">Username</label>
															<input id="name" type="text" class="form-control form-control-lg" name="username" required autocomplete="username" autofocus>
														</div>
                                                    </div>
                                                    <div class="form-row">
														<div class="form-group col">
															<label class="font-weight-bold text-dark text-2">E-mail Address</label>
															<input type="email" class="form-control fomr-control-lg" name="email" required autocomplete="email" autofocus>
														</div>
													</div>
                                                    <div class="form-row">
														<div class="form-group col">
															<label class="font-weight-bold text-dark text-2">First Name</label>
															<input id="name" type="text" class="form-control form-control-lg" name="first_name" required autocomplete="first_name" autofocus>
														</div>
                                                    </div>
                                                    <div class="form-row">
														<div class="form-group col">
															<label class="font-weight-bold text-dark text-2">Last Name</label>
															<input id="name" type="text" class="form-control form-control-lg" name="last_name" required autocomplete="last_name" autofocus>
														</div>
													</div>
                                                    <input id="is_admin" type="hidden" name="is_admin" value=0>
													<div class="form-row">
														<div class="form-group col">
															<label class="font-weight-bold text-dark text-2">Password</label>
															<input type="password" class="form-control form-control-lg" name="password" required autocomplete="current-password">
                                                        </div>
													</div>
                                                    <!--<div class="form-row">
														<div class="form-group col">
															<label class="font-weight-bold text-dark text-2">Confirm Password</label>
															<input id="password-confirm" type="password" class="form-control form-control-lg" name="password_confirmation" required autocomplete="new-password">
                                                        </div>
													</div>-->
													<div class="form-row">
														<div class="form-group col">
															<input type="submit" value="Register" class="btn btn-primary btn-modern float-right" data-loading-text="Loading...">
														</div>
													</div>
												</form>
											</div>
										</div>
									</div>
									<div class="col-md-3"></div>
								</div>

							</div>
						</div>
					</div>

				</div>

            </div>
        
			{% include "trafficapp/footer.html" %}
		</div>
		{% include "trafficapp/foot.html" %}
    </body>
</html>

templates/trafficapp/user/footer.html
<footer class="footer">
    <div class="container-fluid">
        <nav class="float-left">
        <ul>
            <li>
            <a href="#">
                Traffic Generator
            </a>
            </li>
            <li>
            <a href="">
                About Us
            </a>
            </li>
            <li>
            <a href="">
                Licenses
            </a>
            </li>
        </ul>
        </nav>
        <div class="copyright float-right">
        &copy;
        <script>
            document.write(new Date().getFullYear())
        </script> Powered By
        <a href="https://www.esquall.com/" target="_blank"><b>eSquall Inc.</b></a>
        </div>
    </div>
</footer>

templates/trafficapp/user/head.html
{% load static %}

<meta charset="utf-8" />
<link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
<link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
<!--     Fonts and icons     -->
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
<!-- CSS Files -->
<link href="{% static 'assets/css/material-dashboard.css' %}" rel="stylesheet" />
<!-- CSS Just for demo purpose, don't include it in your project -->
<link href="{% static 'assets/demo/demo.css' %}" rel="stylesheet" />
<script src="{% static 'assets/js/core/jquery.min.js' %}"></script>